### PR TITLE
Parse dependency qlfiles on install and update

### PR DESCRIPTION
**Pull request by daewok**
This branch gets qlot to take qlfiles in (most) dependencies into account. It isn't quite ready for merging yet, but I'd like to open it now to see if there is feedback.

One remaining issue is deciding where the qlfiles are located. When running `qlot:install` or `qlot:update`, the qlfile for the system is determined using `asdf:component-pathname`, which requires the ASD file to be loaded and allows a toplevel `:pathname` argument in the `asdf:defsystem` to change where the qlfile is looked for. This seems suboptimal when looking for a dependency's qlfile as ASD files can contain aribtrary code other than the system definitions (grumble). This code instead assumes that dependency qlfiles are in the root of the directory, avoiding the need to load system definitions. If that's acceptable, install and update should probably be changed as well.

This also will not check any dependencies retrieved from Quicklisp for qlfiles, but that seems like correct behavior.

I'll also work on tests for this functionality. Do you have any of your publicly accessible projects that use qlfiles? Or should I make simple systems just for testing purposes?

### CODE REVIEW

**Comment by fukamachi** [comment]
Great!
I've been thinking how this feature could be done.

> This seems suboptimal when looking for a dependency's qlfile as ASD files can contain aribtrary code other than the system definitions (grumble).

Right. This is the difficult part to deal ASD files.
It would be acceptable that it assumes the qlfile locates at the root of the project for now.

Qlot parses `:defsystem-depends-on` in compile-time by attaching `*macroexpand-hook*`.
However, it loads ASD files anyway.
https://github.com/fukamachi/qlot/blob/master/src/source.lisp#L245-L273

> Do you have any of your publicly accessible projects that use qlfiles?

Nope.

CC @Rudolph-Miller

**Comment by Rudolph-Miller** [comment]
LGTM

**Comment by daewok** [comment]
Hey, sorry for disappearing, real life got really got in the way for a while. In the meantime though, I've been reading up more on Bundler and realized it doesn't parse the dependencies Gemfiles at all. It makes sense why: code is less complicated and it lets the top-level application have more control, e.g. A depends on B which depends on v1.1 of C in its Gemfile, but A really needs v1.2 of C for its purposes.

I've managed to accomplish what I was trying to do in a more robust way than I was trying to do here. So I'm happy to let this PR drop without being merged. But if you want, I can finish it off (if so, I'd like to add a keyword argument to qlot:install and update to enable or disable this feature (disabled by default).

**Comment by mtstickney** [comment]
I'm new to this party (I use qlot for a bunch of projects at work, though), so I hope I'm not misunderstanding, but my two cents is that I'm not sure this feature is a good idea.

If I read it right, this essentially adds pinned inter-library dependencies, like those available in npm or bundler or crate or apt. Dependency pinning is great for applications, but I don't think it makes sense for libraries[1]. Why? First, because any library that requires a qlfile is un-quicklispable by definition. Second, because dependency resolution [is NP-complete](https://research.swtch.com/version-sat): for practical purposes you have to fall back to heuristics and other guesswork (and I don't need any more of that near my build process). Finally, it prevents application authors from manually updating a dep that they know will be compatible with their use-case, even if upstream can't or won't use it[2]. Personally, I think it also removes one of the only incentives people have to put effort into preserving compatibility with their libraries.

qlot has a perfect niche already: if pinned inter-library dependencies are like debian or ubuntu packages, the alternative is a rolling-release model where packages all get updated together. This is exactly how quicklisp dists work, but sometimes you want a _different_ dist: qlot lets you create and maintain custom quicklisp dists, and it does a great job at it. I think trying to turn it into Bundler is just going to invite Gem Hell[3].

[1] ..and since applications don't generally depend on other applications, I think that's the real use-case here.
[2] I've done this on more than a few occasions when I needed to get a bugfix out in the field before I could get a patch accepted upstream. You might still be able to do this, but only if you add some mechanism for some qlfiles to override others, and now things are starting to get awfully complex.
[3] Go ahead, try to install a rails app on windows. I _dare_ you. I couldn't even get Redmine up on a Linux box in an evening, due entirely to gem dependency problems.

**Pull request closed without merging**
