### PR TITLE
Added a 'dist' command to use custom Quicklisp distributions

### PR DESCRIPTION
**Pull request by svetlyak40wt**
This pull request adds ability to define and use custom Quicklisp distributions, as suggested in https://github.com/fukamachi/qlot/issues/58:

```
dist ultralisp http://dist.ultralisp.org/

ql :all :latest
ultralisp weblocks 20180827-194049

github slynk joaotavora/sly
…
```

I think code should be refactored a little bit before this pull can be merged.

### CODE REVIEW

**Comment by fukamachi** [comment]
Wow, I'm happy to see like this big contribution.
ultralisp is also a great project and I'd like to encourage.

**Comment by svetlyak40wt** [comment]
I'll finish work on this pull in day or two.

**Comment by svetlyak40wt** [comment]
Fukamachi-san, please, review this pull. Seems it is ready now.

**Comment by fukamachi** [comment]
Thanks!

**Pull request merged**
