### PR TITLE
without clack

### PR DESCRIPTION
**Pull request by snmsts**
From quicklisp 2016-01-21, it support defining uri scheme to process.
This patch define "qlot://" scheme for quicklisp and get rid of clack dependency.

There could have some benefit.

* Generally speaking  the less dependent , would be the better. 
* Local file copy could be faster than http get.
* No requirement for multi-threaded implementations.

I don't finish rewrite tests yet, so some remaining tasks I'll do for this branch.
But purpose for making pull request now is I'd like to hear opinion about the idea of this patch.

### CODE REVIEW

**Comment by fukamachi** [comment]
Sounds pretty great.
Clack (& Hunchentoot) is a big dependency of Qlot and it has been making slow down installing processes.
Besides that, Qlot.server is the most complicated part in Qlot.
Removing it seems to be simply good direction to go.

I suppose, randomize the HTTP port can also be thrown away.
So, the dist URLs looks like `qlot://localhost:3000` (fixed port) or `qlot://localhost`.

**Comment by snmsts** [comment]
I just omitted  tests related to server (cause it's not used anymore) and it passed.
Please review it. I hope there's no drawback by taking it.

**Comment by fukamachi** [comment]
The tests don't pass on my machine.

```
Running a test file '/Users/nitro_idiot/Programs/lib/qlot/tests/main.lisp'
1..6

Installing Quicklisp to /Users/nitro_idiot/Programs/lib/qlot/tests/tmp/quicklisp/ ...
  ✓ can install Quicklisp

  ✓ can uninstall all dists

Reading '/Users/nitro_idiot/Programs/lib/qlot/tests/data/qlfile'...
Installing dist "quicklisp" version "2017-04-03".
;; Accessing to http://beta.quicklisp.org/dist/quicklisp/2017-04-03/distinfo.txt
Installing dist "clack".
;; Accessing to qlot://localhost/clack.txt
While evaluating the form starting at line 39, column 0
  of #P"/Users/nitro_idiot/Programs/lib/qlot/tests/main.lisp":

debugger invoked on a UIOP/RUN-PROGRAM:SUBPROCESS-ERROR in thread
#<THREAD "main thread" RUNNING {1001BBF553}>:
  Subprocess with command "/usr/local/bin/ros roswell-internal-use download qlot://localhost/clack.txt /Users/nitro_idiot/Programs/lib/qlot/tests/tmp/quicklisp/tmp/install-dist-distinfo.txt 2"
 exited with error code 2

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE           ] IGNORE-ERROR-STATUS
  1: [RETRY              ] Retry EVAL of current toplevel form.
  2:                       Ignore error and continue loading file "/Users/nitro_idiot/Programs/lib/qlot/tests/main.lisp".
  3: [ABORT              ] Abort loading file "/Users/nitro_idiot/Programs/lib/qlot/tests/main.lisp".
  4: [SKIP-TEST-FILE     ] Skip this test file.
  5: [SKIP-ALL-TEST-FILES] Give up all test files.
  6:                       Exit debugger, returning to top level.

(UIOP/RUN-PROGRAM::%CHECK-RESULT 2 :COMMAND "/usr/local/bin/ros roswell-internal-use download qlot://localhost/clack.txt /Users/nitro_idiot/Programs/lib/qlot/tests/tmp/quicklisp/tmp/install-dist-distinfo.txt 2" :PROCESS NIL :IGNORE-ERROR-STATUS NIL)
0] backtrace 20

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001BBF553}>
0: (UIOP/RUN-PROGRAM::%CHECK-RESULT 2 :COMMAND "/usr/local/bin/ros roswell-internal-use download qlot://localhost/clack.txt /Users/nitro_idiot/Programs/lib/qlot/tests/tmp/quicklisp/tmp/install-dist-distinfo.txt 2" :PROCESS NIL :IGNORE-ERROR-STATUS NIL)
1: ((LAMBDA (UIOP/RUN-PROGRAM::REDUCED-INPUT #:G8184) :IN UIOP/RUN-PROGRAM::%USE-SYSTEM) NIL #<unavailable argument>)
2: ((FLET #:BEFORE7702 :IN UIOP/RUN-PROGRAM::%CALL-WITH-PROGRAM-IO) #P"/var/folders/cp/fx39lrg11_d31yg3wnhbsm_h0000gn/T/tmp9V47YWQF.tmp")
3: (UIOP/STREAM:CALL-WITH-TEMPORARY-FILE #<CLOSURE (FLET #:BEFORE7702 :IN UIOP/RUN-PROGRAM::%CALL-WITH-PROGRAM-IO) {19FE7AB}> :WANT-STREAM-P NIL :WANT-PATHNAME-P T :DIRECTION :IO :KEEP NIL :AFTER NIL :DIRECTORY NIL :TYPE "tmp" :PREFIX NIL :SUFFIX NIL :ELEMENT-TYPE NIL :EXTERNAL-FORMAT NIL)
4: ((LABELS UIOP/RUN-PROGRAM::HARD-CASE :IN UIOP/RUN-PROGRAM::%CALL-WITH-PROGRAM-IO))
5: (UIOP/RUN-PROGRAM::%USE-SYSTEM "/usr/local/bin/ros roswell-internal-use download qlot://localhost/clack.txt /Users/nitro_idiot/Programs/lib/qlot/tests/tmp/quicklisp/tmp/install-dist-distinfo.txt 2" :INPUT NIL :ERROR-OUTPUT :INTERACTIVE :IF-INPUT-DOES-NOT-EXIST :ERROR :IF-OUTPUT-EXISTS :OVERWRITE :IF-ERROR-OUTPUT-EXISTS :OVERWRITE :ELEMENT-TYPE :DEFAULT :EXTERNAL-FORMAT :UTF-8 :OUTPUT #<BROADCAST-STREAM {100213AA93}> :ERROR-OUTPUT :INTERACTIVE)
6: (ROSWELL:ROSWELL ("roswell-internal-use" "download" "qlot://localhost/clack.txt" #P"/Users/nitro_idiot/Programs/lib/qlot/tests/tmp/quicklisp/tmp/install-dist-distinfo.txt" "2") #<BROADCAST-STREAM {100213AA93}> NIL)
7: ((LAMBDA (QL-SETUP::URL QL-SETUP::FILE &KEY :FOLLOW-REDIRECTS :QUIETLY :MAXIMUM-REDIRECTS) :IN "/Users/nitro_idiot/.roswell/lisp/quicklisp/local-init/ros-download.lisp") #<QL-HTTP:URL "qlot://localhost/clack.txt"> #P"/Users/nitro_idiot/Programs/lib/qlot/tests/tmp/quicklisp/tmp/install-dist-distinfo.txt" :FOLLOW-REDIRECTS #<unused argument> :QUIETLY #<unused argument> :MAXIMUM-REDIRECTS #<unused argument>)
8: (QL-DIST:INSTALL-DIST #<QL-HTTP:URL "qlot://localhost/clack.txt"> :PROMPT NIL :REPLACE NIL)
9: (QLOT/INSTALL::INSTALL-SOURCE #<QLOT.SOURCE.GIT:SOURCE-GIT clack https://github.com/fukamachi/clack.git>)
10: (QLOT/INSTALL::APPLY-QLFILE-TO-QLHOME #P"/Users/nitro_idiot/Programs/lib/qlot/tests/data/qlfile" #P"/Users/nitro_idiot/Programs/lib/qlot/tests/tmp/quicklisp/" :IGNORE-LOCK NIL)
11: (QLOT/INSTALL:INSTALL-QLFILE #P"/Users/nitro_idiot/Programs/lib/qlot/tests/data/qlfile" :QUICKLISP-HOME #P"/Users/nitro_idiot/Programs/lib/qlot/tests/tmp/quicklisp/")
12: (SB-INT:SIMPLE-EVAL-IN-LEXENV (INSTALL (ASDF/SYSTEM:SYSTEM-RELATIVE-PATHNAME :QLOT #P"tests/data/qlfile") :QUICKLISP-HOME (MERGE-PATHNAMES #P"quicklisp/" *TMP-DIRECTORY*)) #<NULL-LEXENV>)
13: (SB-EXT:EVAL-TLF (INSTALL (ASDF/SYSTEM:SYSTEM-RELATIVE-PATHNAME :QLOT #P"tests/data/qlfile") :QUICKLISP-HOME (MERGE-PATHNAMES #P"quicklisp/" *TMP-DIRECTORY*)) 10 NIL)
14: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (INSTALL (ASDF/SYSTEM:SYSTEM-RELATIVE-PATHNAME :QLOT #P"tests/data/qlfile") :QUICKLISP-HOME (MERGE-PATHNAMES #P"quicklisp/" *TMP-DIRECTORY*)) 10)
15: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (INSTALL (ASDF/SYSTEM:SYSTEM-RELATIVE-PATHNAME :QLOT #P"tests/data/qlfile") :QUICKLISP-HOME (MERGE-PATHNAMES #P"quicklisp/" *TMP-DIRECTORY*)) :CURRENT-INDEX 10)
16: (SB-C::%DO-FORMS-FROM-INFO #<CLOSURE (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {10052B713B}> #<SB-C::SOURCE-INFO {10052B70F3}> SB-C::INPUT-ERROR-IN-LOAD)
17: (SB-INT:LOAD-AS-SOURCE #<SB-INT:FORM-TRACKING-STREAM for "file /Users/nitro_idiot/Programs/lib/qlot/tests/main.lisp" {10052B42C3}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
18: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<SB-INT:FORM-TRACKING-STREAM for "file /Users/nitro_idiot/Programs/lib/qlot/tests/main.lisp" {10052B42C3}> NIL)
19: (LOAD #P"/Users/nitro_idiot/Programs/lib/qlot/tests/main.lisp" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :UTF-8)
```

Roswell is v17.4.8.76, the latest version.

Probably, this is Roswell's migration issue.
Roswell stopped rewriting `ql-http:http-fetch`, however, it maybe still remains in the dumped core.

**Comment by fukamachi** [comment]
I don't feel like to say "Please update Roswell, delete `~/.roswell` and execute `ros install fukamachi/qlot for updating Qlot` to every Qlot users.
I hope Roswell will have something good.

**Comment by snmsts** [comment]
Patch for quicklisp was terrible before...
I think migration problem will not appear after
https://github.com/roswell/roswell/commit/512c023acc7fd530f8cf0fdf900002d1c20c9da7

and I changed patch filename from ``ros-download.lisp`` to ``roswell.lisp`` so...

```
(delete-file (ql:qmerge "local-init/ros-download.lisp"))
(roswell:roswell '("download.force=t" "install" "quicklisp"))
```

will do.

**Comment by snmsts** [comment]
@fukamachi isn't it sufficient?

**Comment by fukamachi** [comment]
Merged. Thanks!

**Pull request merged**
