### PR TITLE
Prevent autocrlf for 'git' projects

### PR DESCRIPTION
**Pull request by fukamachi**
ref #18

### CODE REVIEW

**Comment by fukamachi** [comment]
@mtstickney 
Could you test this branch ("autocrlf") to work as you expected?

**Comment by mtstickney** [comment]
I gave this a look after work, with mixed results. The the repo in the local-quicklisp temp folder has the right line endings; I'm currently getting an error in `QLOT.ARCHIVE:CREATE-TARBALL`. It looks like the paths being passed to `ARCHIVE::CREATE-TAR-FILE` are bad (they've got a `:HOST` component, but it's a relative path, e.g. `#P"c:oe-encode\README.org"`). I think that's a separate error, but I don't have time to look into it deeply at the moment.

**Comment by fukamachi** [comment]
It sounds a different Windows-specific problem :(

**Comment by mtstickney** [comment]
I believe it's an issue with `ARCHIVE` on windows, yes. I may look into that later, but there's another option that might be useful to you: rather than cloning a repo and making a tarball yourself, would it be reasonable to use `git archive --format=tar.gz --remote=<repo url>` to just get a tarball directly? Might actually be a small performance boost too...

**Comment by fukamachi** [comment]
It sounds great, but I want to know if it's possible because it would be an obstacle for implementing another "source" which uses "archive".
I made a small change in https://github.com/fukamachi/qlot/commit/bd77abc2fc9976d589bc78171b78aed9cd6ed605. Could you try it again when you have time?

**Comment by mtstickney** [comment]
I made that same patch locally when I was poking around, and it unfortunately doesn't fix the error. The issue is something in an `SB-POSIX:FSTAT` call that `ARCHIVE` is making (something to do with a bad control block). I'll try to dig into that more this weekend.

The relative paths look right with your fix in place, despite the other error; I think it's a keeper.

**Comment by fukamachi** [comment]
Okay, it sounds hard to look into and fix it, so I rewrote it to use "git archive" for now.

**Comment by fukamachi** [comment]
Merging, as I assume it doesn't break on non-Windows OSes anyway.

**Comment by mtstickney** [comment]
Just a heads up, @froydnj merged my fix for the archive library; you should be able to use it instead of "git archive" now. Let me know if you need testing on Windows.

**Pull request merged**
